<a href="https://colab.research.google.com/github/ysargar500/Assign_LetsGradeup/blob/main/assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#Itarative for 1D array

In [ ]:
import numpy as np

In [ ]:
arr_1=np.array([5,8,9])

In [ ]:
for X in arr_1:
  print(X)

5
8
9


In [ ]:
#Itrative for 2D array

In [ ]:
arr_2=np.array([[5,8,9],[12,16,18]])

In [ ]:
for X in arr_2:
  print(X)

[5 8 9]
[12 16 18]


In [ ]:
#itrative for 3D

In [ ]:
arr_3 = np.array([[[5,8,9],[12,16,18]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
for X in arr_3:
  print(X)

[[ 5  8  9]
 [12 16 18]]
[[ 7  8  9]
 [10 11 12]]
